---- YA
CREATE TABLE ABONADO(
    IDENTIDAD_ABONADO NVARCHAR2(15),
    PNOMBRE NVARCHAR2(50),
    SNOMBRE NVARCHAR2(50),
    PAPELLIDO NVARCHAR2(50),
    SAPELLIDO NVARCHAR2(50),
    TELEFONO NVARCHAR2(50),
    CORREO NVARCHAR2(50),
    ESTADO NUMBER(4),
    CONSTRAINT PK_ABONADOS PRIMARY KEY (IDENTIDAD_ABONADO)
);
---- YA
CREATE TABLE SIS_AGUA(
    ID_SIS_A NVARCHAR2(10),
    DESCRIPCION NVARCHAR2(500),
    UBICACION NVARCHAR2(1000),
    CONSTRAINT PK_ID_SIS_A PRIMARY KEY (ID_SIS_A)

);
---- YA
CREATE TABLE SIS_DESECHOS(
    ID_SIS_D NVARCHAR2(10),
    DESCRIPCION NVARCHAR2(500),
    UBICACION NVARCHAR2(1000),
    CONSTRAINT PK_ID_SIS_D PRIMARY KEY (ID_SIS_D)

);
---- YA

CREATE TABLE BARRIOS_COL (
    CODIGO_BARRIO NVARCHAR2(5),
    NOMBRE_BARRIO NVARCHAR2(100),
    CONSTRAINT PK_BARRIOS PRIMARY KEY (CODIGO_BARRIO)
);

CREATE TABLE PROPIEDADES (
    CODIGO_PROPIEDAD NVARCHAR2(20),
    DESCRIPCION NVARCHAR2(500),
    CODIGO_BARRIO NVARCHAR2(5),
    N_MANZANA NVARCHAR2(10),
    N_CASA NVARCHAR2(10),
    IDENTIDAD_ABONADO NVARCHAR2(15),
    FECHA_CONEXION DATE,
    SIS_AGUA NVARCHAR2(10), 
    SIS_DESECHOS NVARCHAR2(10),
    CONSTRAINT PK_PROPIEDAD PRIMARY KEY (CODIGO_PROPIEDAD),
 CONSTRAINT FK_COD_BARRIO FOREIGN KEY (CODIGO_BARRIO) REFERENCES BARRIOS_COL(CODIGO_BARRIO),
 CONSTRAINT FK_IDENTIDAD_ABONADO FOREIGN KEY (IDENTIDAD_ABONADO) REFERENCES ABONADO(IDENTIDAD_ABONADO),
 CONSTRAINT FK_SIS_AGUA FOREIGN KEY (SIS_AGUA) REFERENCES SIS_AGUA(ID_SIS_A),
 CONSTRAINT FK_SIS_DESECHOS FOREIGN KEY (SIS_DESECHOS) REFERENCES SIS_DESECHOS(ID_SIS_D)
);


CREATE TABLE NEGOCIOS(
    CODIGO_NEGOCIO NVARCHAR2(30),
    NOMBRE_NEGOCIO NVARCHAR2(400),
    CODIGO_BARRIO NVARCHAR2(5),
    TELEFONO NVARCHAR2(25),
    IDENTIDAD_ABONADO NVARCHAR2(15),
    SIS_DESECHOS NVARCHAR2(10),
    N_PERMISO NVARCHAR2(10),
    CONSTRAINT PK_CODIGO_NEGOCIO PRIMARY KEY (CODIGO_NEGOCIO),
 CONSTRAINT FK_COD_BARRIO_N FOREIGN KEY (CODIGO_BARRIO) REFERENCES BARRIOS_COL(CODIGO_BARRIO),
 CONSTRAINT FK_IDENTIDAD_ABONADO_N FOREIGN KEY (IDENTIDAD_ABONADO) REFERENCES ABONADO(IDENTIDAD_ABONADO),
 CONSTRAINT FK_SIS_DESECHOS_N FOREIGN KEY (SIS_DESECHOS) REFERENCES SIS_DESECHOS(ID_SIS_D)
);


CREATE TABLE TIPO_PAGO (
    COD_TIPO_PAGO NVARCHAR2 (10),
    DESCRIPCION NVARCHAR2 (100),
    CONSTRAINT PK_TIPO_PAGO PRIMARY KEY (COD_TIPO_PAGO)
);


CREATE TABLE PAGOS (
    ID_PAGO NUMBER,
    COD_TIPO_PAGO NVARCHAR2(10),
    IDENTIDAD_ABONADO NVARCHAR2(15),
    FECHA DATE,
    ID_SERVICIO NVARCHAR2(50),
    CONSTRAINT PK_ID_PAGO PRIMARY KEY (ID_PAGO),
 CONSTRAINT FK_IDENTIDAD_ABONADO_P FOREIGN KEY (IDENTIDAD_ABONADO) REFERENCES ABONADO(IDENTIDAD_ABONADO),
 CONSTRAINT FK_TIPOPAGO_P FOREIGN KEY (COD_TIPO_PAGO) REFERENCES TIPO_PAGO(COD_TIPO_PAGO),
 CONSTRAINT FK_SERVICIO_P FOREIGN KEY (ID_SERVICIO) REFERENCES SERVICIOS(ID_SERVICIO)
 );
DROP TABLE ABONADO;
DROP TABLE PAGOS;
ALTER TABLE PAGOS DROP CONSTRAINT FK_IDENTIDAD_ABONADO_P;
delete from pagos; 
DROP TABLE DETALLE_PAGO;


CREATE TABLE DETALLE_PAGO (
   ID_DETALLE NUMBER,
   ID_PAGO NUMBER,
   CODIGO_PROPIEDAD NVARCHAR2(20),
   CODIGO_NEGOCIO NVARCHAR2(30),
   SALDOS NUMBER,
   ENERO NUMBER,
   FEBRERO NUMBER,
   MARZO NUMBER,
   ABRIL NUMBER,
   MAYO NUMBER,
   JUNIO NUMBER,
   JULIO NUMBER,
   AGOSTO NUMBER,
   SEPTIEMBRE NUMBER,
   OCTUBRE NUMBER,
   NOVIEMBRE NUMBER,
   DICIEMBRE NUMBER,
   ANIO NUMBER,
   PAGO_COMPLETO NVARCHAR2(2),
   CONSTRAINT PK_ID_DETALLE PRIMARY KEY (ID_DETALLE),
   CONSTRAINT FK_ID_PAGO_D FOREIGN KEY (ID_PAGO) REFERENCES PAGOS(ID_PAGO),
   CONSTRAINT FK_CODIGO_PROPIEDAD_D FOREIGN KEY (CODIGO_PROPIEDAD) REFERENCES PROPIEDADES(CODIGO_PROPIEDAD),
   CONSTRAINT FK_CODIGO_NEGOCIO_D FOREIGN KEY (CODIGO_NEGOCIO) REFERENCES NEGOCIOS(CODIGO_NEGOCIO)
);


SELECT * FROM PAGOS;
DROP TABLE DETALLE_PAGO;

 DROP TABLE SERVICIOS;
CREATE TABLE SERVICIOS (
    ID_SERVICIO NVARCHAR2(5),
    SERVICIO NVARCHAR2(50),
    CONSTRAINT PK_ID_SERVICIO PRIMARY KEY (ID_SERVICIO)
);



CREATE TABLE PRUEBA (
    VALOR NUMBER
);


select * 
from pagos
inner join detalle_pago
on pagos.id_pago = detalle_pago.id_pago
; 